"""Tenant_Creation_v2

Revision ID: aa7c62e6f17d
Revises: f54e2a9fbe6b
Create Date: 2024-12-29 17:41:07.278400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7c62e6f17d'
down_revision: Union[str, None] = 'f54e2a9fbe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
