"""Tenant_Creation_v1

Revision ID: f54e2a9fbe6b
Revises: a913cb2aefbf
Create Date: 2024-12-29 17:39:18.073668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f54e2a9fbe6b'
down_revision: Union[str, None] = 'a913cb2aefbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Prospectus_id', table_name='Prospectus')
    op.drop_table('Prospectus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prospectus',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subscription', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('requester_first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requester_last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requester_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requester_phone_number_country_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requester_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requester_designation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Prospectus_pkey'),
    sa.UniqueConstraint('requester_email', name='Prospectus_requester_email_key'),
    sa.UniqueConstraint('slug', name='Prospectus_slug_key'),
    sa.UniqueConstraint('title', name='Prospectus_title_key')
    )
    op.create_index('ix_Prospectus_id', 'Prospectus', ['id'], unique=False)
    # ### end Alembic commands ###
