name: Automate Pipeline

on:
  push:
    branches:
      - main
      - '*' # Matches all branches
jobs:
  Build-and-Package:
    name: Build and Package
    runs-on: ubuntu-latest
    container: docker:20.10.7
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # Checkout the correct branch name
          fetch-depth: 0  # Ensure full history is fetched, useful for Git operations during publish.
      - name: Build
        run: sh ./automate.sh --Target Build
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Runner-Artifacts
          path: Build-Runner-Artifacts/

  Generate-Semantic-Version:
    name: Generate Semantic Version
    runs-on: ubuntu-latest
    needs:
      - Build-and-Package
    outputs:
      semantic_version: ${{ steps.version_step.outputs.FullSemVer }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched.
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      - name: Output FullSemVer
        run: |
          echo "FullSemVer: ${{ steps.version_step.outputs.FullSemVer }}"

  Publish-Stable-Branch-Artifacts:
    name: Publish Stable Branch Artifacts
    runs-on: ubuntu-latest
    container: docker:20.10.7
    needs:
      - Build-and-Package
      - Generate-Semantic-Version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched.
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-Runner-Artifacts
          path: ./Build-Runner-Artifacts/
      - name: Publish
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
          GHP_STV: ${{ needs.Generate-Semantic-Version.outputs.semantic_version }}
        run: |
          echo "TargetSemanticVersion: ${{ needs.Generate-Semantic-Version.outputs.semantic_version }}"
          sh ./automate.sh --Target Publish
#
#    Publish-Stable-Branch-Artifacts1:
#    name: Publish Stable Branch Artifacts1
#    runs-on: ubuntu-latest
#    needs:
#      - Build-and-Package
##    if: github.ref == 'refs/heads/main'
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0  # Ensure full history is fetched, useful for Git operations during publish.
#      - name: Install GitVersion
#        uses: gittools/actions/gitversion/setup@v3.1.1
#        with:
#          versionSpec: '5.x'
#      - name: Determine Version
#        id: version_step
#        uses: gittools/actions/gitversion/execute@v3.1.1
#        with:
#          useConfigFile: true
#          configFilePath: GitVersion.yml
#      - name: Output FullSemVer
#        run: |
#          echo "FullSemVer: ${{ steps.version_step.outputs.FullSemVer }}"
#      - name: Download Artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: Build-Runner-Artifacts
#          path: ./Build-Runner-Artifacts/
#      - name: Publish
#        container: docker:20.10.7
#        env:
#          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
#        run: |
#          echo "TargetSemanticVersion: ${{ steps.version_step.outputs.FullSemVer }}"
#          sh ./automate.sh --Target Publish --Version ${{ steps.version_step.outputs.FullSemVer }}
#





#
#  Container-Image-Scan:
#    name: Container Image Scan
#    runs-on: ubuntu-latest
#    container: docker:20.10.7
#    needs: Build-and-Package
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#      - name: Scan
#        run: sh ./automate.sh --Target Scan
#      - name: Save Artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: Build-Runner-Artifacts
#          path: Build-Runner-Artifacts
#



#

#  Publish-Artifacts-Stable-Branch:
#    name: Publish Artifacts (Stable Branch)
#    runs-on: ubuntu-latest
#    container: docker:20.10.7
#    needs:
#      - Build-and-Package
##      - Container-Image-Scan
#    if: github.ref == 'refs/heads/main'
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#      - name: Download Artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: Build-Runner-Artifacts
#          path: ./Build-Runner-Artifacts/  # Directory where artifacts will be downloaded.
#      - name: Publish
#        run: sh ./automate.sh --Target Publish
#      - name: Clean Workspace
#        run: sh ./automate.sh --Target CleanWorkspace
#
#  Publish-Artifacts-UnStable-Branch:
#    name: Publish Artifacts (Unstable Branch)
#    runs-on: ubuntu-latest
#    container: docker:20.10.7
#    needs:
#      - Build-and-Package
#      - Container-Image-Scan
#    if: github.ref != 'refs/heads/main'
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#      - name: Publish
#        run: sh ./automate.sh --Target Publish
#      - name: Clean Workspace
#        run: sh ./automate.sh --Target CleanWorkspace
