name: IHCE.SaasOps.Automate.Builder

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request: null
  workflow_dispatch: null

env:
  _Variables: ${{ toJson(vars) }}
  _Secrets: ${{ toJson(secrets) }}

jobs:
  Build-Build-and-Package:
    name: Build-Build-and-Package
    runs-on: ubuntu-latest
    container: docker:20.10.7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Run Automate Script
        run: sh ./automate.sh --Target Build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Runner-Artifacts
          path: Build-Runner-Artifacts/
          if-no-files-found: ignore

  Build-Verbosity-and-Diagnostic:
    name: Build-Verbosity-and-Diagnostic
    runs-on: ubuntu-latest
    needs:
      - Build-Build-and-Package
    outputs:
      semantic_version: ${{ steps.version_step.outputs.FullSemVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Setup Semantic GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '5.x'
          preferLatestVersion: true
      - name: Execute Semantic GitVersion
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

  Build-Run-Security-Scan:
    name: Build-Run-Security-Scan
    runs-on: ubuntu-latest
    container: docker:20.10.7
    needs:
      - Build-Build-and-Package
      - Build-Verbosity-and-Diagnostic
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-Runner-Artifacts
          path: ./Build-Runner-Artifacts/
      - run: |
          echo "Invoking Container Image Security Scanning"
          sh ./automate.sh --Target Scan
    if: github.ref == 'refs/heads/main'

  Publish-Publish-Artifacts-Stable-Branch:
    name:  Publish-Publish-Artifacts-Stable-Branch
    runs-on: ubuntu-latest
    container: docker:20.10.7
    needs:
      - Build-Build-and-Package
      - Build-Run-Security-Scan
      - Build-Verbosity-and-Diagnostic
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-Runner-Artifacts
          path: ./Build-Runner-Artifacts/
      - name: Publish
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
          GHP_TargetVersion: ${{ needs.Build-Verbosity-and-Diagnostic.outputs.semantic_version }}
        run: |
          echo "Invoking Artifact Publishing"
          sh ./automate.sh --Target Publish
    if: github.ref == 'refs/heads/main'

  Publish-Publish-Artifacts-Unstable-Branch:
    name: Publish-Publish-Artifacts-Unstable-Branch
    runs-on: ubuntu-latest
    container: docker:20.10.7
    needs:
      - Build-Build-and-Package
      - Build-Run-Security-Scan
      - Build-Verbosity-and-Diagnostic
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-Runner-Artifacts
          path: ./Build-Runner-Artifacts/
      - name: Publish
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
          GHP_TargetVersion: ${{ needs.Build-Verbosity-and-Diagnostic.outputs.semantic_version }}
        run: |
          echo "Invoking Artifact Publishing"
          sh ./automate.sh --Target Publish
    if: github.ref != 'refs/heads/main'
